# Generated by Django 5.1.7 on 2026-04-15 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='edition',
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='BorrowTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.edition')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='circulation.borrowtransaction')),
            ],
        ),
    ]
