# Generated by Django 5.1.7 on 2026-04-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_remove_borrowtransaction_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('BORROWED', 'Borrowed'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
